project_id = "bujspkrjmcobqyyppcej"

[auth]
# image = "v2.184.0"
[functions.process-subscription]
enabled = true
verify_jwt = false
entrypoint = "./functions/process-subscription/index.ts"

[functions.ai-pricing]
enabled = true
verify_jwt = false

[functions.ai-vision]
enabled = true
verify_jwt = false

[functions.content-generation]
enabled = true
verify_jwt = false

[functions.chatbot]
enabled = true
verify_jwt = false
