
-- Add identity verification columns to bnpl_applications
ALTER TABLE public.bnpl_applications
ADD COLUMN IF NOT EXISTS applicant_phone text,
ADD COLUMN IF NOT EXISTS applicant_id_number text,
ADD COLUMN IF NOT EXISTS id_card_url text,
ADD COLUMN IF NOT EXISTS photo_url text,
ADD COLUMN IF NOT EXISTS contract_signed_at timestamptz;

-- Create storage bucket for detailed documents if it doesn't exist
INSERT INTO storage.buckets (id, name, public)
VALUES ('bnpl-documents', 'bnpl-documents', false)
ON CONFLICT (id) DO NOTHING;

-- Policy to allow authenticated users to upload their own documents
CREATE POLICY "Users can upload their own BNPL documents"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK ( bucket_id = 'bnpl-documents' AND auth.uid() = owner );

-- Policy to allow users to view their own documents
CREATE POLICY "Users can view their own BNPL documents"
ON storage.objects FOR SELECT
TO authenticated
USING ( bucket_id = 'bnpl-documents' AND auth.uid() = owner );

-- Policy for Merchants to view documents linked to their products' applications
-- Note: This is complex in storage policies because it requires joining. 
-- For simplicity in this local setup, we might allow authenticated users to read if they have the valid URL, 
-- OR strictly relying on Signed URLs generated by the server/client for display.
-- Let's stick to signed URLs for specific access or broad authenticated read for now if low urgency on strict isolation.
-- For better security:
-- We will rely on Signed URLs which bypass RLS for viewing.
