// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  throw new Error('Les variables VITE_SUPABASE_URL et VITE_SUPABASE_ANON_KEY doivent être définies dans .env');
}

if (import.meta.env.DEV) {
  console.log('--- SUPABASE CLIENT CONFIG (DEV) ---');
  console.log('URL:', SUPABASE_URL);
  console.log('Mode:', SUPABASE_URL.includes('localhost') || SUPABASE_URL.includes('127.0.0.1') ? 'LOCAL' : 'CLOUD');
  console.log('------------------------------------');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);